### ISSUE TITLE
Unclickable footer links in IE 11

### ISSUE THREAD

**Issue by simonswiss** [IainAndrew/footer-reveal#1]
Great plugin, thanks for open-sourcing it 1 :+1: 

On IE11, the margin seems to sit over the footer area, and therefore any link / button cannot be clicked. The issue is also present in your demo.

**Comment by IainAndrew** [comment]
Sorry for not getting back to you on this, I'll look into it.

**Comment by Nemvts** [comment]
You will have to actually target the HTML element and apply the CSS property of margin-bottom for this to work on IE 11.

**Comment by IainAndrew** [comment]
A solution to this issue is to set the 'zIndex' property on your footerReveal instance to 0 (or anything higher than -1), and, in your css, set the z-index of your main content to 1 (or anything higher than the value of your footerReveal's zIndex property).
Demo here - http://codepen.io/overflowhidden/pen/ZePMyq
